# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

target 'tesseract' do
  pod 'TesseractOCRiOS', :git => 'https://github.com/gali8/Tesseract-OCR-iOS.git', :branch => 'master'
end

target 'tesseractTests' do

end

target 'tesseractUITests' do

end